/** Declaration file generated by dts-gen */

export function bisect(f: any, a: any, b: any, parameters: any): any;

export function conjugateGradient(f: any, initial: any, params: any): any;

export function gradientDescent(f: any, initial: any, params: any): any;

export function gradientDescentLineSearch(f: any, initial: any, params: any): any;

export function nelderMead(f: (x: number[], grad?: number[]) => number, x0: number[], parameters?: {}): {x: number[]};

export function norm2(a: any): any;

export function scale(ret: any, value: any, c: any): void;

export function weightedSum(ret: any, w1: any, v1: any, w2: any, v2: any): void;

export function zeros(x: any): any;

export function zerosM(x: any, y: any): any;
